(ns docker-m3958.const
  (:require [docker-m3958.jutil :as jutil])
  (:gen-class))

(def DB-PATH
  (if (jutil/is-windows)
    "c:/db/hsqldb"
    "/opt/db/hsqldb"))

(def id-field [:id "INTEGER GENERATED BY DEFAULT AS IDENTITY" :PRIMARY :KEY])

(def TABLE-DSCS
  {
   :apptpl [:apptpl
             id-field
             [:name "VARCHAR(64)"]
             [:desc "VARCHAR(1000)"]]
   :app [:app
         id-field
         [:name "VARCHAR(64)"]
         [:desc "VARCHAR(1000)"]]
   :image [:image
         id-field
         [:name "VARCHAR(64)"]
         [:desc "VARCHAR(1000)"]
         [:image_type "VARCHAR(32)"] ;service vol
         [:cport "INTEGER"]
         [:iname "VARCHAR(64)"]]
   :apptpl_image [:apptpl_image
         [:apptpl_id "INTEGER REFERENCES apptpl(id)"]
         [:image_id "INTEGER REFERENCES image(id)"]]
   :host [:host
         id-field
         [:name "VARCHAR(64)"]
         [:url "VARCHAR(64)"]]
   :container [:container
         id-field
         [:image_id "INTEGER REFERENCES image(id)"]
         [:host_id "INTEGER REFERENCES host(id)"]
         [:rname "VARCHAR(64)"]
         [:name "INTEGER NOT NULL"]
         [:hport "INTEGER"]
         [:ctype "VARCHAR(32)"] ;service,service-vol,web-vol
         [:volume_from "VARCHAR(1000)"]
         [:links "VARCHAR(1000)"]
         ["UNIQUE (host_id, name)"]]
   })
